languaje: java
jdk:
- oraclejdk7
cache:
  directories:
  - gen-budge
  - gen-budge/node_modules
before_script:
- git clone https://github.com/jirsis/gen-budge.git
script:
- cd progen
- mvn clean verify site jacoco:report coveralls:jacoco
after_script:
- node -v
- cd ../gen-budge
- npm install
- ./gen-budges.js ../progen/target/
after_success:
  - git config user.email "travis@travis-ci.org"
  - git config user.name "Travis-CI deplyer"
  - git clone https://${GH_TOKEN}@github.com/pro-gen/pro-gen.github.io.git
  - cd pro-gen.github.io
  - cp gen-budge/*svg .
  - git add -f *svg
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to ProGen page"
  - git push -fq origin gh-pages
env:
  global:
    secure: dEs2TyS0sPMhO9EYp4a3Krf2e3oDitQmmSedUr5NOhHeJYT0hryB+u6rk0ouExg6XIcENP34pZiTTT3Ko9en04BiJG7MVJb+J+TG6OZeXPLqTDjFGW1RIHMwS0tG5wUyA7d2SYGGwfv2pqM/D5grqfyKjwNQ38/HsWbqr5PMRx0=
