languaje: java
jdk:
- oraclejdk7
cache:
  directories:
    - gen-budge
    - node_modules
before_script:
  #- sudo apt-get update -q
  #- sudo apt-get install nodejs
  - git clone https://github.com/jirsis/gen-bugde.git
  - pwd
script:
- cd progen
- mvn clean verify site jacoco:report coveralls:jacoco
- cd ../
after_script:
- node -v
- cd ./gen-budge
- npm install
- ./gen-budge.js ../target/
- ls ../target/
- pwd
