languaje: java
jdk:
- oraclejdk7
cache:
  directories:
  - $TRAVIS_BUILD_DIR/gen-budge/node_modules
before_script:
- git clone https://github.com/jirsis/gen-budge.git $TRAVIS_BUILD_DIR/gen-budge
- git clone https://${GH_TOKEN}@github.com/pro-gen/pro-gen.github.io.git $TRAVIS_BUILD_DIR/pro-gen.github.io
script:
- cd progen
- mvn clean verify site jacoco:report coveralls:jacoco
after_success:
  - node -v
  - cd $TRAVIS_BUILD_DIR/gen-budge
  - npm install
  - ./gen-budges.js $TRAVIS_BUILD_DIR/progen/target/
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis-CI deployer"
  - cd $TRAVIS_BUILD_DIR/pro-gen.github.io
  - cp -v $TRAVIS_BUILD_DIR/progen/target/*svg .
  - cp -vr $TRAVIS_BUILD_DIR/progen/target/site reports
  - git add -f *svg
  - git add -f reports/*
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to ProGen page"
  - git push -fq origin master
env:
  global:
    secure: dEs2TyS0sPMhO9EYp4a3Krf2e3oDitQmmSedUr5NOhHeJYT0hryB+u6rk0ouExg6XIcENP34pZiTTT3Ko9en04BiJG7MVJb+J+TG6OZeXPLqTDjFGW1RIHMwS0tG5wUyA7d2SYGGwfv2pqM/D5grqfyKjwNQ38/HsWbqr5PMRx0=
