languaje: java
jdk:
- oraclejdk7
cache:
  directories:
    - gen-budge
    - node_modules
before_script:
  - sudo apt-get update -q
  - sudo apt-get install nodejs
  - git clone https://github.com/jirsis/gen-bugde.git
  - export PATH=$PATH:gen-budge/
  - npm install
script:
- node -v
- cd progen
- mvn clean verify site jacoco:report coveralls:jacoco
- gen-budge.js target/
- ls target/
